server:
  port: 8081

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
      driver-class-name: ${fakeupwork.datasource.driver-class-name}
      url: jdbc:mysql://${fakeupwork.datasource.host}:${fakeupwork.datasource.port}/${fakeupwork.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${fakeupwork.datasource.username}
      password: ${fakeupwork.datasource.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wyc.pojo.Entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

wyc:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    secret-key: fakeupworkwyc
    # 设置jwt过期时间
    ttl: 7200000
    # 设置前端传递过来的令牌名称
    token-name: token
